---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyplex-watched

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-jellyplex-watched
commonLabels:
  app: jellyplex-watched

resources:
- resources/configmaps.yaml
- resources/cronjobs.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml

images:
  - name: jellyplex-watched
    newName: ghcr.io/luigi311/jellyplex-watched
    newTag: 8.5.0
