---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyplex-watched

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-jellyplex-watched
commonLabels:
  app: jellyplex-watched

resources:
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/namespaces.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: jellyplex-watched
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
